### ISSUE TITLE
[EPIC] Support try_* functions which always return NULL instead of runtime errors

### ISSUE THREAD

**Issue by advancedxy** [apache/arrow-datafusion-comet#280]
Spark adds a lot of try_* functions in the recent two years, which always return NULL instead of runtime errors. The list is as follows:
- [x] try_add
- [x] try_divide
- [x] try_subtract
- [x] try_multiply
- [x] try_element_at
- [x] try_avg
- [x] try_sum
- [x] try_to_binary
- [x] try_to_timestamp
- [x] try_aes_decrypt
- [-] ~~try_reflect~~  (cannot be supported in Comet?)
- [x] try_cast (part of https://github.com/apache/datafusion-comet/issues/286)

We should add  support to these functions too. It could be implemented in Comet first then contributed back to upstream DataFusion.

_Originally posted by @viirya in https://github.com/apache/arrow-datafusion-comet/pull/277#discussion_r1568139442_

**Comment by andygrove** [comment]
I added `try_cast` to a list, with a link to the cast epic

**Comment by coderfender** [comment]
time to revisit this EPIC given that a bunch of them (if not all) are now supported in comet ?

**Comment by coderfender** [comment]
Closing this issue since ANSI mode is now supported
